import type { ActivityType } from "@pims/db";

export interface DetailField {
  key: string;
  label: string;
  type?: "text" | "number" | "select";
  options?: string[];
}

export interface ActivityConfig {
  slug: string;
  activityType: ActivityType;
  title: string;
  description: string;
  zone: "pre-welding" | "post-welding" | "crossing" | "cms";
  usesStationRange: boolean;
  usesWeldRange: boolean;
  detailFields: DetailField[];
}

export const ACTIVITY_CONFIGS: ActivityConfig[] = [
  {
    slug: "route-survey",
    activityType: "ROUTE_SURVEY",
    title: "Route Survey",
    description: "Route Survey, ROW, Trenching, Stringing and Bending activities are tracked here.",
    zone: "pre-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "alignmentSheetNumber", label: "Alignment Sheet Number" },
      { key: "typeOfTerrain", label: "Type of Terrain" },
      { key: "typeOfSoil", label: "Type of Soil" },
      { key: "reRouting", label: "Re Routing" },
    ],
  },
  {
    slug: "row",
    activityType: "ROW_HANDOVER",
    title: "ROW Handover",
    description: "Right of way handover with coordinate capture.",
    zone: "pre-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "alignmentSheetNumber", label: "Alignment Sheet Number" },
      { key: "typeOfTerrain", label: "Type of Terrain" },
      { key: "typeOfSoil", label: "Type of Soil" },
      { key: "reRouting", label: "Re Routing" },
      { key: "coordNorth", label: "Coordinate North", type: "number" },
      { key: "coordEast", label: "Coordinate East", type: "number" },
    ],
  },
  {
    slug: "clearing-grading",
    activityType: "CLEARING_GRADING",
    title: "Clearing & Grading",
    description: "Clearing and grading of the right of way.",
    zone: "pre-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "alignmentSheetNumber", label: "Alignment Sheet Number" },
      { key: "typeOfTerrain", label: "Type of Terrain" },
      { key: "typeOfSoil", label: "Type of Soil" },
      { key: "reRouting", label: "Re Routing" },
    ],
  },
  {
    slug: "trenching",
    activityType: "TRENCHING",
    title: "Trenching",
    description: "Trench excavation along the route.",
    zone: "pre-welding",
    usesStationRange: true,
    usesWeldRange: true,
    detailFields: [
      { key: "alignmentSheetNumber", label: "Alignment Sheet Number" },
      { key: "depth", label: "Depth", type: "number" },
      { key: "trenchWidth", label: "Trench Width", type: "number" },
      { key: "bottomWidth", label: "Bottom Width", type: "number" },
      { key: "rockyGroundTrench", label: "Rocky Ground Trench", type: "select", options: ["Yes", "No"] },
      { key: "typeOfGround", label: "Type of Ground" },
    ],
  },
  {
    slug: "stringing",
    activityType: "STRINGING",
    title: "Stringing",
    description: "Placing a physical pipe joint at its route location. Marks the pipe as Strung.",
    zone: "pre-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "itemNumber", label: "Item Number (Pipe No)" },
      { key: "heatNo", label: "Heat No" },
      { key: "length", label: "Length", type: "number" },
      { key: "wallThickness", label: "Wall Thickness", type: "number" },
      { key: "diameter", label: "Diameter", type: "number" },
      { key: "coatingNo", label: "Coating No" },
      { key: "alignmentSheetNumber", label: "Alignment Sheet Number" },
      { key: "crossingNo", label: "Crossing No" },
      { key: "coatingDamage", label: "Coating Damage", type: "select", options: ["None", "Minor", "Major"] },
    ],
  },
  {
    slug: "bending",
    activityType: "BENDING",
    title: "Pipe Cold Bending",
    description: "Cold bending of a pipe joint, with QC checks.",
    zone: "pre-welding",
    usesStationRange: false,
    usesWeldRange: false,
    detailFields: [
      { key: "itemNumber", label: "Item Number (Pipe No)" },
      { key: "chainage", label: "Chainage", type: "number" },
      { key: "bendType1", label: "Bend Type 1" },
      { key: "bendDegree1", label: "Bend Degree 1", type: "number" },
      { key: "bendType2", label: "Bend Type 2" },
      { key: "bendDegree2", label: "Bend Degree 2", type: "number" },
      { key: "bendDirection", label: "Bend Direction" },
      { key: "visualInspection", label: "Visual Inspection (Internal & External)", type: "select", options: ["Yes", "No"] },
      { key: "internalCalibration", label: "Internal Calibration", type: "select", options: ["Accepted", "Not Accepted"] },
      { key: "externalCalibration", label: "External Calibration", type: "select", options: ["Accepted", "Not Accepted"] },
      { key: "gaugePlate", label: "Gauge Plate", type: "select", options: ["Accepted", "Not Accepted"] },
      { key: "holidayTest", label: "Holiday Test", type: "select", options: ["Yes", "No"] },
    ],
  },
  {
    slug: "as-built-survey",
    activityType: "AS_BUILT_SURVEY",
    title: "As-Built Survey",
    description: "Final surveyed as-built geometry per weld span.",
    zone: "pre-welding",
    usesStationRange: true,
    usesWeldRange: true,
    detailFields: [
      { key: "zoneNumber", label: "Zone Number" },
      { key: "coordX", label: "Coordinate From X", type: "number" },
      { key: "coordY", label: "Coordinate From Y", type: "number" },
      { key: "groundElevation", label: "Ground Elevation", type: "number" },
      { key: "pipeTopElevation", label: "Pipe Top Elevation", type: "number" },
      { key: "coverDepth", label: "Cover Depth", type: "number" },
      { key: "surveyCode", label: "Survey Code" },
      { key: "wallThickness", label: "WT (mm)", type: "number" },
    ],
  },
  // --- Post-Welding zone ---
  {
    slug: "joint-coating",
    activityType: "JOINT_COATING",
    title: "Joint Coating",
    description: "Field joint coating applied over a completed weld.",
    zone: "post-welding",
    usesStationRange: false,
    usesWeldRange: true,
    detailFields: [
      { key: "coatingType", label: "Coating Type" },
      { key: "coatingMaterialBatch", label: "Coating Material Batch No" },
      { key: "holidayTest", label: "Holiday Test", type: "select", options: ["Pass", "Fail"] },
      { key: "thickness", label: "Coating Thickness (mm)", type: "number" },
    ],
  },
  {
    slug: "lowering",
    activityType: "LOWERING",
    title: "Lowering",
    description: "Lowering the strung/coated pipe section into the trench.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "coatingConditionCheck", label: "Coating Condition Check", type: "select", options: ["OK", "Not OK"] },
      { key: "paddingUsed", label: "Padding Used", type: "select", options: ["Yes", "No"] },
    ],
  },
  {
    slug: "backfilling",
    activityType: "BACKFILLING",
    title: "Backfilling",
    description: "Backfilling the trench after lowering.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "backfillMaterial", label: "Backfill Material" },
      { key: "compactionCheck", label: "Compaction Check", type: "select", options: ["OK", "Not OK"] },
    ],
  },
  {
    slug: "hydrotest-report",
    activityType: "HYDROTEST_REPORT",
    title: "Hydrostatic Test Report",
    description: "Hydrotest results for a completed hydrotest section.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "testSectionNo", label: "Test Section No" },
      { key: "testPressure", label: "Test Pressure", type: "number" },
      { key: "holdDurationHours", label: "Hold Duration (hrs)", type: "number" },
      { key: "result", label: "Result", type: "select", options: ["Pass", "Fail"] },
    ],
  },
  {
    slug: "weld-repair",
    activityType: "WELD_REPAIR",
    title: "Weld Repair",
    description: "Repair of a weld joint that failed visual or NDT inspection.",
    zone: "post-welding",
    usesStationRange: false,
    usesWeldRange: true,
    detailFields: [
      { key: "repairReason", label: "Reason for Repair" },
      { key: "repairType", label: "Repair Type", type: "select", options: ["Full Cutout", "Partial Repair", "Grinding"] },
      { key: "repairedByWelder", label: "Repaired By (Welder Code)" },
      { key: "retestResult", label: "Retest Result", type: "select", options: ["Accept", "Not Accept"] },
    ],
  },
  {
    slug: "marker-installation",
    activityType: "MARKER_INSTALLATION",
    title: "Marker Installation",
    description: "Installation of route/warning/kilometer markers.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "markerType", label: "Marker Type", type: "select", options: ["Route Marker", "Warning Marker", "Kilometer Marker", "Test Point Marker"] },
      { key: "markerNumber", label: "Marker Number" },
      { key: "coordNorth", label: "Coordinate North", type: "number" },
      { key: "coordEast", label: "Coordinate East", type: "number" },
    ],
  },
  {
    slug: "ofc-splicing-jointing",
    activityType: "OFC_SPLICING_JOINTING",
    title: "OFC Splicing & Jointing",
    description: "Optical fibre cable splicing and joint pit closure.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "splicerName", label: "Splicer Name" },
      { key: "jointPitNo", label: "Joint Pit No" },
      { key: "fiberCount", label: "Fiber Count", type: "number" },
      { key: "spliceLoss", label: "Splice Loss (dB)", type: "number" },
    ],
  },
  {
    slug: "hdpe-duct-laying",
    activityType: "HDPE_DUCT_LAYING",
    title: "HDPE Duct Laying",
    description: "Laying of HDPE duct for OFC alongside the pipeline.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "ductSize", label: "Duct Size" },
      { key: "ductDepth", label: "Duct Depth", type: "number" },
      { key: "jointingMethod", label: "Jointing Method" },
    ],
  },
  {
    slug: "restoration",
    activityType: "RESTORATION",
    title: "Restoration",
    description: "Right of way restoration to original condition after backfilling.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "restorationType", label: "Restoration Type", type: "select", options: ["Agricultural Land", "Road Crossing", "Water Body", "Forest Land"] },
      { key: "landOwnerAcknowledgement", label: "Land Owner Acknowledgement", type: "select", options: ["Yes", "No"] },
    ],
  },
  {
    slug: "pre-hydrotest",
    activityType: "PRE_HYDROTEST",
    title: "Pre-Hydrotest",
    description: "Pre-hydrotest readiness checks for a test section.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "testSectionNo", label: "Test Section No" },
      { key: "endClosureType", label: "End Closure Type" },
      { key: "fillMedium", label: "Fill Medium", type: "select", options: ["Water", "Air"] },
      { key: "readinessCheck", label: "Readiness Check", type: "select", options: ["OK", "Not OK"] },
    ],
  },
  {
    slug: "temporary-cathodic-protection",
    activityType: "TEMPORARY_CATHODIC_PROTECTION",
    title: "Temporary Cathodic Protection",
    description: "Temporary CP applied during construction to control corrosion.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "anodeType", label: "Anode Type" },
      { key: "potentialReading", label: "Potential Reading (mV)", type: "number" },
    ],
  },
  {
    slug: "cleaning-gauging",
    activityType: "CLEANING_GAUGING",
    title: "Cleaning & Gauging",
    description: "Pipeline internal cleaning and gauging pig run before hydrotest.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "testSectionNo", label: "Test Section No" },
      { key: "pigType", label: "Pig Type" },
      { key: "gaugePlateResult", label: "Gauge Plate Result", type: "select", options: ["OK", "Not OK"] },
      { key: "deformation", label: "Deformation (%)", type: "number" },
    ],
  },
  {
    slug: "swabbing-dewatering",
    activityType: "SWABBING_DEWATERING",
    title: "Swabbing & Dewatering",
    description: "Post-hydrotest swabbing and dewatering of the test section.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "testSectionNo", label: "Test Section No" },
      { key: "swabRuns", label: "Number of Swab Runs", type: "number" },
      { key: "dewateringMethod", label: "Dewatering Method" },
      { key: "result", label: "Result", type: "select", options: ["Complete", "Incomplete"] },
    ],
  },
  {
    slug: "magnetic-cleaning",
    activityType: "MAGNETIC_CLEANING",
    title: "Magnetic Cleaning",
    description: "Magnetic pig run to remove ferrous debris from the pipeline.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "testSectionNo", label: "Test Section No" },
      { key: "pigRuns", label: "Number of Runs", type: "number" },
      { key: "debrisCollected", label: "Debris Collected", type: "select", options: ["Yes", "No"] },
    ],
  },
  {
    slug: "egp",
    activityType: "EGP",
    title: "EGP (Electronic Geometry Pigging)",
    description: "Electronic geometry pig run to verify pipe roundness/ovality.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "testSectionNo", label: "Test Section No" },
      { key: "maxOvality", label: "Max Ovality (%)", type: "number" },
      { key: "result", label: "Result", type: "select", options: ["Pass", "Fail"] },
    ],
  },
  {
    slug: "ofc-blowing",
    activityType: "OFC_BLOWING",
    title: "OFC Blowing",
    description: "Blowing optical fibre cable through the installed HDPE duct.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "cableType", label: "Cable Type" },
      { key: "blowingLength", label: "Blowing Length (m)", type: "number" },
      { key: "result", label: "Result", type: "select", options: ["OK", "Not OK"] },
    ],
  },
  {
    slug: "ofc-joint-pits",
    activityType: "OFC_JOINT_PITS",
    title: "OFC Joint Pits",
    description: "Excavation and closure of OFC joint pits.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "jointPitNo", label: "Joint Pit No" },
      { key: "pitDepth", label: "Pit Depth", type: "number" },
      { key: "closureStatus", label: "Closure Status", type: "select", options: ["Open", "Closed"] },
    ],
  },
  {
    slug: "nitrogen-purging",
    activityType: "NITROGEN_PURGING",
    title: "Nitrogen Purging",
    description: "Nitrogen purging of the test section after dewatering.",
    zone: "post-welding",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "testSectionNo", label: "Test Section No" },
      { key: "oxygenLevelBefore", label: "Oxygen Level Before (%)", type: "number" },
      { key: "oxygenLevelAfter", label: "Oxygen Level After (%)", type: "number" },
    ],
  },
  // --- Crossing zone ---
  {
    slug: "hdd-crossing",
    activityType: "HDD_CROSSING",
    title: "HDD Crossing",
    description: "Horizontal Directional Drilling crossing execution (road/river/rail).",
    zone: "crossing",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "crossingNo", label: "Crossing No" },
      { key: "crossingType", label: "Crossing Type", type: "select", options: ["Road", "River", "Railway", "Canal"] },
      { key: "entryAngle", label: "Entry Angle", type: "number" },
      { key: "exitAngle", label: "Exit Angle", type: "number" },
      { key: "drillLength", label: "Drill Length (m)", type: "number" },
      { key: "drillingContractor", label: "Drilling Contractor" },
    ],
  },
  {
    slug: "crossing-detail",
    activityType: "CROSSING_DETAIL",
    title: "Crossing Detail",
    description: "Detailed crossing-level record linked to a Line Crossing master entry.",
    zone: "crossing",
    usesStationRange: true,
    usesWeldRange: false,
    detailFields: [
      { key: "crossingNo", label: "Crossing No" },
      { key: "protectionMethod", label: "Protection Method", type: "select", options: ["Casing Pipe", "Concrete Slab", "HDD", "Open Cut"] },
      { key: "casingPipeSize", label: "Casing Pipe Size" },
      { key: "vents", label: "Vents Installed", type: "select", options: ["Yes", "No"] },
    ],
  },
  // --- CMS / QC upload zone ---
  {
    slug: "cms-activity-uploader",
    activityType: "CMS_ACTIVITY_UPLOAD",
    title: "CMS Activity Uploader",
    description: "Reference record for a Construction Management System activity file uploaded outside PIMS.",
    zone: "cms",
    usesStationRange: false,
    usesWeldRange: false,
    detailFields: [
      { key: "activityName", label: "Activity Name" },
      { key: "uploadReference", label: "File Name / Reference" },
      { key: "uploadedBy", label: "Uploaded By" },
    ],
  },
  {
    slug: "qc-activity-uploader",
    activityType: "QC_ACTIVITY_UPLOAD",
    title: "QC Activity Uploader",
    description: "Reference record for a Quality Control activity file uploaded outside PIMS.",
    zone: "cms",
    usesStationRange: false,
    usesWeldRange: false,
    detailFields: [
      { key: "activityName", label: "QC Activity Name" },
      { key: "uploadReference", label: "File Name / Reference" },
      { key: "uploadedBy", label: "Uploaded By" },
    ],
  },
];

export function getActivityConfig(slug: string) {
  return ACTIVITY_CONFIGS.find((c) => c.slug === slug);
}

export function activitiesForZone(zone: ActivityConfig["zone"]) {
  return ACTIVITY_CONFIGS.filter((c) => c.zone === zone);
}
